INSERT INTO transformers2 (name)
VALUES
    ('Optimus Prime'),
    ('Bumblebee'),
    ('Megatron'),
    ('Starscream'),
    ('Soundwave'),
    ('Shockwave'),
    ('Ironhide'),
    ('Ratchet'),
    ('Jazz'),
    ('Prowl'),
    ('Wheeljack'),
    ('Arcee'),
    ('Grimlock'),
    ('Sideswipe'),
    ('Mirage'),
    ('Hound'),
    ('Ultra Magnus'),
    ('Hot Rod'),
    ('Kup'),
    ('Blurr'),
    ('Galvatron'),
    ('Thundercracker'),
    ('Skywarp'),
    ('Barricade'),
    ('Blackout'),
    ('Frenzy'),
    ('Rumble'),
    ('Devastator'),
    ('Bonecrusher'),
    ('Scrapper'),
    ('Long Haul'),
    ('Mixmaster'),
    ('Scavenger'),
    ('Overhaul'),
    ('Drift'),
    ('Crosshairs'),
    ('Windblade'),
    ('Bulkhead'),
    ('Perceptor');